// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR42GFH7gszEWMOfzmLWmOYatvBBYj-B0',
    appId: '1:827176675042:web:c132fef088db2bd7e9a0bb',
    messagingSenderId: '827176675042',
    projectId: 'precinho-dd1c9',
    authDomain: 'precinho-dd1c9.firebaseapp.com',
    storageBucket: 'precinho-dd1c9.firebasestorage.app',
    measurementId: 'G-LDPX19149Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2aCiUIpAmvlEXk24HIj1JqiA4ksPpQXg',
    appId: '1:827176675042:android:00781a4ec7162b73e9a0bb',
    messagingSenderId: '827176675042',
    projectId: 'precinho-dd1c9',
    storageBucket: 'precinho-dd1c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxQ7-LvkV8cNUIlE3chU7ziBclKc7XMs',
    appId: '1:827176675042:ios:278a838c2e9fdff0e9a0bb',
    messagingSenderId: '827176675042',
    projectId: 'precinho-dd1c9',
    storageBucket: 'precinho-dd1c9.firebasestorage.app',
    iosBundleId: 'com.precinho.precinhoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxQ7-LvkV8cNUIlE3chU7ziBclKc7XMs',
    appId: '1:827176675042:ios:278a838c2e9fdff0e9a0bb',
    messagingSenderId: '827176675042',
    projectId: 'precinho-dd1c9',
    storageBucket: 'precinho-dd1c9.firebasestorage.app',
    iosBundleId: 'com.precinho.precinhoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR42GFH7gszEWMOfzmLWmOYatvBBYj-B0',
    appId: '1:827176675042:web:8bc7d1410ddaa855e9a0bb',
    messagingSenderId: '827176675042',
    projectId: 'precinho-dd1c9',
    authDomain: 'precinho-dd1c9.firebaseapp.com',
    storageBucket: 'precinho-dd1c9.firebasestorage.app',
    measurementId: 'G-93NLEPJF1D',
  );
}
