// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: AppConfig.get('FIREBASE_WEB_API_KEY',
            defaultValue: 'AIzaSyDR42GFH7gszEWMOfzmLWmOYatvBBYj-B0'),
        appId: AppConfig.get('FIREBASE_WEB_APP_ID',
            defaultValue: '1:827176675042:web:c132fef088db2bd7e9a0bb'),
        messagingSenderId: AppConfig.get('FIREBASE_WEB_MESSAGING_SENDER_ID',
            defaultValue: '827176675042'),
        projectId:
            AppConfig.get('FIREBASE_PROJECT_ID', defaultValue: 'precinho-dd1c9'),
        authDomain: AppConfig.get('FIREBASE_WEB_AUTH_DOMAIN',
            defaultValue: 'precinho-dd1c9.firebaseapp.com'),
        storageBucket: AppConfig.get('FIREBASE_STORAGE_BUCKET',
            defaultValue: 'precinho-dd1c9.firebasestorage.app'),
        measurementId: AppConfig.get('FIREBASE_MEASUREMENT_ID',
            defaultValue: 'G-LDPX19149Y'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: AppConfig.get('FIREBASE_ANDROID_API_KEY',
            defaultValue: 'AIzaSyC2aCiUIpAmvlEXk24HIj1JqiA4ksPpQXg'),
        appId: AppConfig.get('FIREBASE_ANDROID_APP_ID',
            defaultValue: '1:827176675042:android:00781a4ec7162b73e9a0bb'),
        messagingSenderId: AppConfig.get('FIREBASE_ANDROID_MESSAGING_SENDER_ID',
            defaultValue: '827176675042'),
        projectId:
            AppConfig.get('FIREBASE_PROJECT_ID', defaultValue: 'precinho-dd1c9'),
        storageBucket: AppConfig.get('FIREBASE_STORAGE_BUCKET',
            defaultValue: 'precinho-dd1c9.firebasestorage.app'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: AppConfig.get('FIREBASE_IOS_API_KEY',
            defaultValue: 'AIzaSyBlxQ7-LvkV8cNUIlE3chU7ziBclKc7XMs'),
        appId: AppConfig.get('FIREBASE_IOS_APP_ID',
            defaultValue: '1:827176675042:ios:278a838c2e9fdff0e9a0bb'),
        messagingSenderId: AppConfig.get('FIREBASE_IOS_MESSAGING_SENDER_ID',
            defaultValue: '827176675042'),
        projectId:
            AppConfig.get('FIREBASE_PROJECT_ID', defaultValue: 'precinho-dd1c9'),
        storageBucket: AppConfig.get('FIREBASE_STORAGE_BUCKET',
            defaultValue: 'precinho-dd1c9.firebasestorage.app'),
        iosBundleId: 'com.precinho.precinhoApp',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: AppConfig.get('FIREBASE_IOS_API_KEY',
            defaultValue: 'AIzaSyBlxQ7-LvkV8cNUIlE3chU7ziBclKc7XMs'),
        appId: AppConfig.get('FIREBASE_IOS_APP_ID',
            defaultValue: '1:827176675042:ios:278a838c2e9fdff0e9a0bb'),
        messagingSenderId: AppConfig.get('FIREBASE_IOS_MESSAGING_SENDER_ID',
            defaultValue: '827176675042'),
        projectId:
            AppConfig.get('FIREBASE_PROJECT_ID', defaultValue: 'precinho-dd1c9'),
        storageBucket: AppConfig.get('FIREBASE_STORAGE_BUCKET',
            defaultValue: 'precinho-dd1c9.firebasestorage.app'),
        iosBundleId: 'com.precinho.precinhoApp',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: AppConfig.get('FIREBASE_WEB_API_KEY',
            defaultValue: 'AIzaSyDR42GFH7gszEWMOfzmLWmOYatvBBYj-B0'),
        appId: AppConfig.get('FIREBASE_WEB_APP_ID',
            defaultValue: '1:827176675042:web:8bc7d1410ddaa855e9a0bb'),
        messagingSenderId: AppConfig.get('FIREBASE_WEB_MESSAGING_SENDER_ID',
            defaultValue: '827176675042'),
        projectId:
            AppConfig.get('FIREBASE_PROJECT_ID', defaultValue: 'precinho-dd1c9'),
        authDomain: AppConfig.get('FIREBASE_WEB_AUTH_DOMAIN',
            defaultValue: 'precinho-dd1c9.firebaseapp.com'),
        storageBucket: AppConfig.get('FIREBASE_STORAGE_BUCKET',
            defaultValue: 'precinho-dd1c9.firebasestorage.app'),
        measurementId: AppConfig.get('FIREBASE_MEASUREMENT_ID',
            defaultValue: 'G-93NLEPJF1D'),
      );
}
